name: Full-Stack HTTP Monitor CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  backend-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Backend - Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Backend - Run Linter
        working-directory: ./backend
        run: npm run lint

      - name: Backend - Run Tests
        working-directory: ./backend
        env:
          MONGO_URI: mongodb://localhost:27017/test-db
        run: npm run test

  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Frontend - Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Frontend - Run Linter
        working-directory: ./frontend
        run: npm run lint

      - name: Frontend - Build
        working-directory: ./frontend
        run: npm run build
